name: Build,Push Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: java-goof
  DOCKER_USERNAME: omearaj

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      #env:
      #  SNYK_API_TOKEN: ${{ secrets.SNYK_API_TOKEN }} 
      run: |
        mvn install --file pom.xml -Prun-its

  # Push image to Container Registry
  push:
    # Ensure test job passes before pushing image.
    needs: build
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    #permissions:
    #  packages: write
    #  contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: omearaj/java-goof/java-goof
          tag_with_ref: true
    
 #   steps:
 #   - uses: actions/checkout@v2
 #     name: Check out code

 #   - uses: mr-smithers-excellent/docker-build-push@v5
 #     name: Build & push Docker image
 #     with:
 #       image: ${{ env.IMAGE_NAME }}
 #       tags: v1, latest
 #       registry: ghcr.io
 #       dockerfile: Dockerfile
 #       username: ${{ env.DOCKER_USERNAME }}
 #       password: ${{ secrets.GITHUB_TOKEN }}
